# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96df30c63da6739109a483bcb3a33a97df69904b264134adb841a2f35ae0872234e68bdf00c7ae843dc9f3ef9963756bbf276e7b70557f55446944d8b3bf3383

test:
  secret_key_base: 8b69b0d0964f30300e84e5bc06e24dc9c5137e86a89f690149d2f1ef3b1646ac052fa88ddcb8a5ade79a438c70b2422d3b0b8442a234a38a9a07e744da435d3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
